"""baseline_2026_02_25

Revision ID: d187588fa76d
Revises: 
Create Date: 2026-02-25 12:58:06.775505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd187588fa76d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agencies')),
    schema='core'
    )
    op.create_table('favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('listing_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    schema='core'
    )
    op.create_index('idx_favorites_user_listing', 'favorites', ['user_id', 'listing_id'], unique=True, schema='core')
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('listing_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('medium_url', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    schema='core'
    )
    op.create_table('lead_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('lead_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_notes')),
    schema='core'
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('listing_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_phone_e164', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('preferred_contact_time', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    schema='core'
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.Enum('SYSTEM', 'VERIFICATION', 'LISTING', 'BOOKING', 'SUBSCRIPTION', 'MESSAGE', 'LEAD', 'REVIEW', 'PAYMENT', 'SECURITY', name='template_notification_type'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title_template', sa.Text(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('summary_template', sa.String(length=500), nullable=True),
    sa.Column('default_delivery_methods', sa.JSON(), nullable=True),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='template_priority'), nullable=True),
    sa.Column('allowed_variables', sa.JSON(), nullable=True),
    sa.Column('required_variables', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    schema='core'
    )
    op.create_index(op.f('ix_core_notification_templates_template_key'), 'notification_templates', ['template_key'], unique=True, schema='core')
    op.create_table('performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('unique_count', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('average_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_metrics')),
    schema='core'
    )
    op.create_index(op.f('ix_core_performance_metrics_entity_id'), 'performance_metrics', ['entity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_performance_metrics_entity_type'), 'performance_metrics', ['entity_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_performance_metrics_metric_type'), 'performance_metrics', ['metric_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_performance_metrics_period_start'), 'performance_metrics', ['period_start'], unique=False, schema='core')
    op.create_index(op.f('ix_core_performance_metrics_period_type'), 'performance_metrics', ['period_type'], unique=False, schema='core')
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.Enum('individual_free', 'individual_basic', 'individual_premium', 'enterprise_basic', 'enterprise_premium', 'enterprise_unlimited', name='plan_tier'), nullable=False),
    sa.Column('period', sa.Enum('monthly', 'quarterly', 'yearly', 'permanent', name='plan_period'), nullable=False),
    sa.Column('period_months', sa.Integer(), nullable=False),
    sa.Column('target_user_type', sa.Enum('individual', 'agency', 'both', name='plan_target_type'), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('max_active_listings', sa.Integer(), nullable=False),
    sa.Column('listing_active_days', sa.Integer(), nullable=False),
    sa.Column('max_images_per_listing', sa.Integer(), nullable=False),
    sa.Column('max_videos_per_listing', sa.Integer(), nullable=False),
    sa.Column('max_video_seconds', sa.Integer(), nullable=False),
    sa.Column('max_image_width', sa.Integer(), nullable=False),
    sa.Column('max_image_height', sa.Integer(), nullable=False),
    sa.Column('featured_listings', sa.Boolean(), nullable=False),
    sa.Column('priority_support', sa.Boolean(), nullable=False),
    sa.Column('analytics_access', sa.Boolean(), nullable=False),
    sa.Column('api_access', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code')),
    schema='core'
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    schema='core'
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    schema='core'
    )
    op.create_index(op.f('ix_core_subscription_plans_plan_code'), 'subscription_plans', ['plan_code'], unique=True, schema='core')
    op.create_table('system_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'MAINTENANCE', name='system_status'), nullable=False),
    sa.Column('status_message', sa.String(length=500), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('uptime_percentage', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_healthy_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_health')),
    schema='core'
    )
    op.create_index(op.f('ix_core_system_health_component_name'), 'system_health', ['component_name'], unique=True, schema='core')
    op.create_index(op.f('ix_core_system_health_last_check_at'), 'system_health', ['last_check_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_system_health_status'), 'system_health', ['status'], unique=False, schema='core')
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('instance', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_metrics')),
    schema='core'
    )
    op.create_index(op.f('ix_core_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=False, schema='core')
    op.create_index(op.f('ix_core_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False, schema='core')
    op.create_table('user_agency',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'agency_id', name=op.f('pk_user_agency')),
    schema='core'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.Text(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('national_id', sa.Text(), nullable=True),
    sa.Column('national_id_type', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'tenant', 'landlord', 'agent', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_index(op.f('ix_core_users_firebase_uid'), 'users', ['firebase_uid'], unique=True, schema='core')
    op.create_table('verification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('verification_type', sa.Enum('LISTING', 'AGENCY', 'USER', name='template_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('optional_documents', sa.JSON(), nullable=True),
    sa.Column('verification_steps', sa.JSON(), nullable=True),
    sa.Column('auto_approve_criteria', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_templates')),
    schema='core'
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('listing_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos')),
    schema='core'
    )
    op.create_table('geocode_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_type', sa.String(length=20), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('original_query', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('result_type', sa.Enum('ADDRESS', 'BUSINESS', 'LANDMARK', 'APPROXIMATE', name='geocoderesulttype'), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geocode_cache'))
    )
    op.create_index(op.f('ix_geocode_cache_expires_at'), 'geocode_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_geocode_cache_is_valid'), 'geocode_cache', ['is_valid'], unique=False)
    op.create_index(op.f('ix_geocode_cache_query_hash'), 'geocode_cache', ['query_hash'], unique=True)
    op.create_index(op.f('ix_geocode_cache_query_type'), 'geocode_cache', ['query_type'], unique=False)
    op.create_table('nearby_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_latitude', sa.String(length=20), nullable=False),
    sa.Column('search_longitude', sa.String(length=20), nullable=False),
    sa.Column('search_radius', sa.Integer(), nullable=False),
    sa.Column('place_type', sa.String(length=50), nullable=False),
    sa.Column('place_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=False),
    sa.Column('longitude', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('price_level', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nearby_places'))
    )
    op.create_index(op.f('ix_nearby_places_distance_meters'), 'nearby_places', ['distance_meters'], unique=False)
    op.create_index(op.f('ix_nearby_places_expires_at'), 'nearby_places', ['expires_at'], unique=False)
    op.create_index(op.f('ix_nearby_places_is_active'), 'nearby_places', ['is_active'], unique=False)
    op.create_index(op.f('ix_nearby_places_place_id'), 'nearby_places', ['place_id'], unique=False)
    op.create_index(op.f('ix_nearby_places_place_type'), 'nearby_places', ['place_type'], unique=False)
    op.create_index(op.f('ix_nearby_places_search_latitude'), 'nearby_places', ['search_latitude'], unique=False)
    op.create_index(op.f('ix_nearby_places_search_longitude'), 'nearby_places', ['search_longitude'], unique=False)
    op.create_table('admin_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['core.users.id'], name=op.f('fk_admin_actions_admin_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_actions')),
    schema='core'
    )
    op.create_index(op.f('ix_core_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_admin_actions_created_at'), 'admin_actions', ['created_at'], unique=False, schema='core')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTER', 'USER_UPDATE', 'USER_SUSPEND', 'USER_UNSUSPEND', 'USER_DELETE', 'LISTING_CREATE', 'LISTING_UPDATE', 'LISTING_DELETE', 'LISTING_FLAG', 'LISTING_APPROVE', 'LISTING_REJECT', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SUBSCRIPTION_CREATE', 'SUBSCRIPTION_CANCEL', 'ADMIN_ACCESS', 'SYSTEM_CONFIG', 'DATA_EXPORT', 'SECURITY_EVENT', name='audit_action_type'), nullable=False),
    sa.Column('action_description', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='core'
    )
    op.create_index(op.f('ix_core_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_category'), 'audit_logs', ['category'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='core')
    op.create_table('configuration_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('requires_restart', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['last_modified_by'], ['core.users.id'], name=op.f('fk_configuration_settings_last_modified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_settings')),
    schema='core'
    )
    op.create_index(op.f('ix_core_configuration_settings_category'), 'configuration_settings', ['category'], unique=False, schema='core')
    op.create_index(op.f('ix_core_configuration_settings_key'), 'configuration_settings', ['key'], unique=True, schema='core')
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('property_type', sa.Text(), nullable=False),
    sa.Column('advertiser_type', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('area_built', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('area_total', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_spots', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('rental_term', sa.Text(), nullable=True),
    sa.Column('rental_mode', sa.Text(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('pet_friendly', sa.Boolean(), nullable=True),
    sa.Column('airbnb_score', sa.Integer(), nullable=True),
    sa.Column('airbnb_eligible', sa.Boolean(), nullable=True),
    sa.Column('airbnb_opted_out', sa.Boolean(), nullable=False),
    sa.Column('rental_model', sa.Text(), nullable=True),
    sa.Column('smoking_allowed', sa.Boolean(), nullable=True),
    sa.Column('deposit_required', sa.Boolean(), nullable=False),
    sa.Column('deposit_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('minimum_stay_nights', sa.Integer(), nullable=True),
    sa.Column('maximum_stay_nights', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.Text(), nullable=True),
    sa.Column('check_out_time', sa.Text(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('cleaning_included', sa.Boolean(), nullable=False),
    sa.Column('cleaning_fee', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('utilities_included', sa.Boolean(), nullable=False),
    sa.Column('internet_included', sa.Boolean(), nullable=False),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('available_from', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('contact_phone_e164', sa.Text(), nullable=True),
    sa.Column('contact_whatsapp_phone_e164', sa.Text(), nullable=True),
    sa.Column('contact_whatsapp_link', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('search_doc', postgresql.TSVECTOR(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('leads_count', sa.Integer(), nullable=False),
    sa.Column('favorites_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['core.agencies.id'], name=op.f('fk_listings_agency_id_agencies')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['core.users.id'], name=op.f('fk_listings_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_listings')),
    schema='core'
    )
    op.create_index(op.f('ix_core_listings_owner_user_id'), 'listings', ['owner_user_id'], unique=False, schema='core')
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('system_notifications', sa.JSON(), nullable=True),
    sa.Column('verification_notifications', sa.JSON(), nullable=True),
    sa.Column('listing_notifications', sa.JSON(), nullable=True),
    sa.Column('subscription_notifications', sa.JSON(), nullable=True),
    sa.Column('message_notifications', sa.JSON(), nullable=True),
    sa.Column('lead_notifications', sa.JSON(), nullable=True),
    sa.Column('review_notifications', sa.JSON(), nullable=True),
    sa.Column('payment_notifications', sa.JSON(), nullable=True),
    sa.Column('security_notifications', sa.JSON(), nullable=True),
    sa.Column('digest_frequency', sa.String(length=20), nullable=True),
    sa.Column('digest_time', sa.String(length=5), nullable=True),
    sa.Column('marketing_emails', sa.Boolean(), nullable=True),
    sa.Column('newsletter_subscription', sa.Boolean(), nullable=True),
    sa.Column('sms_verification_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_notification_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_settings')),
    schema='core'
    )
    op.create_index(op.f('ix_core_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=True, schema='core')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('SYSTEM', 'VERIFICATION', 'LISTING', 'BOOKING', 'SUBSCRIPTION', 'MESSAGE', 'LEAD', 'REVIEW', 'PAYMENT', 'SECURITY', name='notification_type'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notification_priority'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='notification_status'), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('delivery_methods', sa.JSON(), nullable=True),
    sa.Column('delivered_via', sa.JSON(), nullable=True),
    sa.Column('failed_deliveries', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='core'
    )
    op.create_index(op.f('ix_core_notifications_created_at'), 'notifications', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notifications_notification_type'), 'notifications', ['notification_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notifications_priority'), 'notifications', ['priority'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notifications_related_entity_id'), 'notifications', ['related_entity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notifications_status'), 'notifications', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='core')
    op.create_table('report_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('report_format', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_report_generations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_generations')),
    schema='core'
    )
    op.create_index(op.f('ix_core_report_generations_user_id'), 'report_generations', ['user_id'], unique=False, schema='core')
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('query_text', sa.String(length=500), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('sort_by', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('results_clicked', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('searched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_search_queries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries')),
    schema='core'
    )
    op.create_index(op.f('ix_core_search_queries_searched_at'), 'search_queries', ['searched_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_search_queries_session_id'), 'search_queries', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_search_queries_user_id'), 'search_queries', ['user_id'], unique=False, schema='core')
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('external_subscription_id', sa.Text(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['core.plans.id'], name=op.f('fk_subscriptions_plan_id_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    schema='core'
    )
    op.create_index(op.f('ix_core_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False, schema='core')
    op.create_table('user_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_description', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_user_activity_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity')),
    schema='core'
    )
    op.create_index(op.f('ix_core_user_activity_activity_type'), 'user_activity', ['activity_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_user_activity_occurred_at'), 'user_activity', ['occurred_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_user_activity_user_id'), 'user_activity', ['user_id'], unique=False, schema='core')
    op.create_table('user_suspensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('suspended_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(), nullable=True),
    sa.Column('lifted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lifted_by'], ['core.users.id'], name=op.f('fk_user_suspensions_lifted_by_users')),
    sa.ForeignKeyConstraint(['suspended_by'], ['core.users.id'], name=op.f('fk_user_suspensions_suspended_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_user_suspensions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_suspensions')),
    schema='core'
    )
    op.create_index(op.f('ix_core_user_suspensions_suspended_at'), 'user_suspensions', ['suspended_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_user_suspensions_user_id'), 'user_suspensions', ['user_id'], unique=False, schema='core')
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('LISTING', 'AGENCY', 'USER', name='verification_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'UNDER_REVIEW', name='verification_status'), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='moderation_priority'), nullable=True),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('requester_notes', sa.Text(), nullable=True),
    sa.Column('moderator_notes', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('submission_count', sa.Integer(), nullable=True),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('review_completed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['core.users.id'], name=op.f('fk_verifications_moderator_id_users')),
    sa.ForeignKeyConstraint(['requester_id'], ['core.users.id'], name=op.f('fk_verifications_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications')),
    schema='core'
    )
    op.create_index(op.f('ix_core_verifications_created_at'), 'verifications', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_verifications_moderator_id'), 'verifications', ['moderator_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_verifications_requester_id'), 'verifications', ['requester_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_verifications_status'), 'verifications', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_verifications_target_id'), 'verifications', ['target_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_verifications_target_type'), 'verifications', ['target_type'], unique=False, schema='core')
    op.create_table('external_api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('request_size', sa.Integer(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_attempt', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_external_api_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_api_logs'))
    )
    op.create_index(op.f('ix_external_api_logs_correlation_id'), 'external_api_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_external_api_logs_duration_ms'), 'external_api_logs', ['duration_ms'], unique=False)
    op.create_index(op.f('ix_external_api_logs_provider'), 'external_api_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_external_api_logs_response_status'), 'external_api_logs', ['response_status'], unique=False)
    op.create_index(op.f('ix_external_api_logs_service'), 'external_api_logs', ['service'], unique=False)
    op.create_index(op.f('ix_external_api_logs_user_id'), 'external_api_logs', ['user_id'], unique=False)
    op.create_table('integration_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT', 'MESSAGING', 'MAPS', 'ANALYTICS', 'STORAGE', name='integrationtype'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('daily_usage', sa.Integer(), nullable=True),
    sa.Column('monthly_usage', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=True),
    sa.Column('avg_response_time', sa.Integer(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], name=op.f('fk_integration_configs_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_configs'))
    )
    op.create_index(op.f('ix_integration_configs_is_active'), 'integration_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_integration_configs_is_healthy'), 'integration_configs', ['is_healthy'], unique=False)
    op.create_index(op.f('ix_integration_configs_name'), 'integration_configs', ['name'], unique=True)
    op.create_index(op.f('ix_integration_configs_provider'), 'integration_configs', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_configs_type'), 'integration_configs', ['type'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('event_action', sa.String(length=100), nullable=False),
    sa.Column('event_label', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['core.listings.id'], name=op.f('fk_analytics_events_listing_id_listings')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_analytics_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events')),
    schema='core'
    )
    op.create_index(op.f('ix_core_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_analytics_events_event_category'), 'analytics_events', ['event_category'], unique=False, schema='core')
    op.create_index(op.f('ix_core_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_analytics_events_listing_id'), 'analytics_events', ['listing_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False, schema='core')
    op.create_table('listing_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('SPAM', 'INAPPROPRIATE', 'FALSE_INFO', 'DUPLICATE', 'FRAUD', 'OTHER', name='listing_flag_reason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['core.users.id'], name=op.f('fk_listing_flags_admin_id_users')),
    sa.ForeignKeyConstraint(['listing_id'], ['core.listings.id'], name=op.f('fk_listing_flags_listing_id_listings')),
    sa.ForeignKeyConstraint(['reported_by'], ['core.users.id'], name=op.f('fk_listing_flags_reported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_flags')),
    schema='core'
    )
    op.create_index(op.f('ix_core_listing_flags_created_at'), 'listing_flags', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_listing_flags_listing_id'), 'listing_flags', ['listing_id'], unique=False, schema='core')
    op.create_table('listing_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('scroll_depth', sa.Integer(), nullable=True),
    sa.Column('images_viewed', sa.Integer(), nullable=True),
    sa.Column('contact_clicked', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['core.listings.id'], name=op.f('fk_listing_views_listing_id_listings')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_listing_views_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_views')),
    schema='core'
    )
    op.create_index(op.f('ix_core_listing_views_listing_id'), 'listing_views', ['listing_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_listing_views_session_id'), 'listing_views', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_listing_views_user_id'), 'listing_views', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_listing_views_viewed_at'), 'listing_views', ['viewed_at'], unique=False, schema='core')
    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['core.users.id'], name=op.f('fk_moderation_actions_moderator_id_users')),
    sa.ForeignKeyConstraint(['verification_id'], ['core.verifications.id'], name=op.f('fk_moderation_actions_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_actions')),
    schema='core'
    )
    op.create_index(op.f('ix_core_moderation_actions_created_at'), 'moderation_actions', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_moderation_actions_moderator_id'), 'moderation_actions', ['moderator_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_moderation_actions_verification_id'), 'moderation_actions', ['verification_id'], unique=False, schema='core')
    op.create_table('moderation_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='queue_priority'), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('processing_started', sa.Boolean(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['core.users.id'], name=op.f('fk_moderation_queue_assigned_to_users')),
    sa.ForeignKeyConstraint(['verification_id'], ['core.verifications.id'], name=op.f('fk_moderation_queue_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_queue')),
    sa.UniqueConstraint('verification_id', name=op.f('uq_moderation_queue_verification_id')),
    schema='core'
    )
    op.create_index(op.f('ix_core_moderation_queue_assigned_to'), 'moderation_queue', ['assigned_to'], unique=False, schema='core')
    op.create_index(op.f('ix_core_moderation_queue_priority'), 'moderation_queue', ['priority'], unique=False, schema='core')
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('delivery_method', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='delivery_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='delivery_status'), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['core.notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    schema='core'
    )
    op.create_index(op.f('ix_core_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False, schema='core')
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('processing', sa.Boolean(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['core.notifications.id'], name=op.f('fk_notification_queue_notification_id_notifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_queue')),
    schema='core'
    )
    op.create_index(op.f('ix_core_notification_queue_notification_id'), 'notification_queue', ['notification_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notification_queue_priority_score'), 'notification_queue', ['priority_score'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notification_queue_scheduled_for'), 'notification_queue', ['scheduled_for'], unique=False, schema='core')
    op.create_table('payment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('external_payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('invoice_url', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['core.subscriptions.id'], name=op.f('fk_payment_history_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_history')),
    schema='core'
    )
    op.create_table('subscription_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('listings_used', sa.Integer(), nullable=True),
    sa.Column('images_uploaded', sa.Integer(), nullable=True),
    sa.Column('videos_uploaded', sa.Integer(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=True),
    sa.Column('limits_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['core.subscriptions.id'], name=op.f('fk_subscription_usage_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_usage')),
    schema='core'
    )
    op.create_table('verification_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['core.users.id'], name=op.f('fk_verification_documents_uploaded_by_users')),
    sa.ForeignKeyConstraint(['verification_id'], ['core.verifications.id'], name=op.f('fk_verification_documents_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_documents')),
    schema='core'
    )
    op.create_index(op.f('ix_core_verification_documents_verification_id'), 'verification_documents', ['verification_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_verification_documents_verification_id'), table_name='verification_documents', schema='core')
    op.drop_table('verification_documents', schema='core')
    op.drop_table('subscription_usage', schema='core')
    op.drop_table('payment_history', schema='core')
    op.drop_index(op.f('ix_core_notification_queue_scheduled_for'), table_name='notification_queue', schema='core')
    op.drop_index(op.f('ix_core_notification_queue_priority_score'), table_name='notification_queue', schema='core')
    op.drop_index(op.f('ix_core_notification_queue_notification_id'), table_name='notification_queue', schema='core')
    op.drop_table('notification_queue', schema='core')
    op.drop_index(op.f('ix_core_notification_deliveries_status'), table_name='notification_deliveries', schema='core')
    op.drop_index(op.f('ix_core_notification_deliveries_notification_id'), table_name='notification_deliveries', schema='core')
    op.drop_table('notification_deliveries', schema='core')
    op.drop_index(op.f('ix_core_moderation_queue_priority'), table_name='moderation_queue', schema='core')
    op.drop_index(op.f('ix_core_moderation_queue_assigned_to'), table_name='moderation_queue', schema='core')
    op.drop_table('moderation_queue', schema='core')
    op.drop_index(op.f('ix_core_moderation_actions_verification_id'), table_name='moderation_actions', schema='core')
    op.drop_index(op.f('ix_core_moderation_actions_moderator_id'), table_name='moderation_actions', schema='core')
    op.drop_index(op.f('ix_core_moderation_actions_created_at'), table_name='moderation_actions', schema='core')
    op.drop_table('moderation_actions', schema='core')
    op.drop_index(op.f('ix_core_listing_views_viewed_at'), table_name='listing_views', schema='core')
    op.drop_index(op.f('ix_core_listing_views_user_id'), table_name='listing_views', schema='core')
    op.drop_index(op.f('ix_core_listing_views_session_id'), table_name='listing_views', schema='core')
    op.drop_index(op.f('ix_core_listing_views_listing_id'), table_name='listing_views', schema='core')
    op.drop_table('listing_views', schema='core')
    op.drop_index(op.f('ix_core_listing_flags_listing_id'), table_name='listing_flags', schema='core')
    op.drop_index(op.f('ix_core_listing_flags_created_at'), table_name='listing_flags', schema='core')
    op.drop_table('listing_flags', schema='core')
    op.drop_index(op.f('ix_core_analytics_events_user_id'), table_name='analytics_events', schema='core')
    op.drop_index(op.f('ix_core_analytics_events_session_id'), table_name='analytics_events', schema='core')
    op.drop_index(op.f('ix_core_analytics_events_listing_id'), table_name='analytics_events', schema='core')
    op.drop_index(op.f('ix_core_analytics_events_event_type'), table_name='analytics_events', schema='core')
    op.drop_index(op.f('ix_core_analytics_events_event_category'), table_name='analytics_events', schema='core')
    op.drop_index(op.f('ix_core_analytics_events_created_at'), table_name='analytics_events', schema='core')
    op.drop_table('analytics_events', schema='core')
    op.drop_index(op.f('ix_integration_configs_type'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_provider'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_name'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_is_healthy'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_is_active'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_external_api_logs_user_id'), table_name='external_api_logs')
    op.drop_index(op.f('ix_external_api_logs_service'), table_name='external_api_logs')
    op.drop_index(op.f('ix_external_api_logs_response_status'), table_name='external_api_logs')
    op.drop_index(op.f('ix_external_api_logs_provider'), table_name='external_api_logs')
    op.drop_index(op.f('ix_external_api_logs_duration_ms'), table_name='external_api_logs')
    op.drop_index(op.f('ix_external_api_logs_correlation_id'), table_name='external_api_logs')
    op.drop_table('external_api_logs')
    op.drop_index(op.f('ix_core_verifications_target_type'), table_name='verifications', schema='core')
    op.drop_index(op.f('ix_core_verifications_target_id'), table_name='verifications', schema='core')
    op.drop_index(op.f('ix_core_verifications_status'), table_name='verifications', schema='core')
    op.drop_index(op.f('ix_core_verifications_requester_id'), table_name='verifications', schema='core')
    op.drop_index(op.f('ix_core_verifications_moderator_id'), table_name='verifications', schema='core')
    op.drop_index(op.f('ix_core_verifications_created_at'), table_name='verifications', schema='core')
    op.drop_table('verifications', schema='core')
    op.drop_index(op.f('ix_core_user_suspensions_user_id'), table_name='user_suspensions', schema='core')
    op.drop_index(op.f('ix_core_user_suspensions_suspended_at'), table_name='user_suspensions', schema='core')
    op.drop_table('user_suspensions', schema='core')
    op.drop_index(op.f('ix_core_user_activity_user_id'), table_name='user_activity', schema='core')
    op.drop_index(op.f('ix_core_user_activity_occurred_at'), table_name='user_activity', schema='core')
    op.drop_index(op.f('ix_core_user_activity_activity_type'), table_name='user_activity', schema='core')
    op.drop_table('user_activity', schema='core')
    op.drop_index(op.f('ix_core_subscriptions_user_id'), table_name='subscriptions', schema='core')
    op.drop_table('subscriptions', schema='core')
    op.drop_index(op.f('ix_core_search_queries_user_id'), table_name='search_queries', schema='core')
    op.drop_index(op.f('ix_core_search_queries_session_id'), table_name='search_queries', schema='core')
    op.drop_index(op.f('ix_core_search_queries_searched_at'), table_name='search_queries', schema='core')
    op.drop_table('search_queries', schema='core')
    op.drop_index(op.f('ix_core_report_generations_user_id'), table_name='report_generations', schema='core')
    op.drop_table('report_generations', schema='core')
    op.drop_index(op.f('ix_core_notifications_user_id'), table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_status'), table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_related_entity_id'), table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_priority'), table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_notification_type'), table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_created_at'), table_name='notifications', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_index(op.f('ix_core_notification_settings_user_id'), table_name='notification_settings', schema='core')
    op.drop_table('notification_settings', schema='core')
    op.drop_index(op.f('ix_core_listings_owner_user_id'), table_name='listings', schema='core')
    op.drop_table('listings', schema='core')
    op.drop_index(op.f('ix_core_configuration_settings_key'), table_name='configuration_settings', schema='core')
    op.drop_index(op.f('ix_core_configuration_settings_category'), table_name='configuration_settings', schema='core')
    op.drop_table('configuration_settings', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_user_id'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_target_type'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_target_id'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_created_at'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_category'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_action_type'), table_name='audit_logs', schema='core')
    op.drop_table('audit_logs', schema='core')
    op.drop_index(op.f('ix_core_admin_actions_created_at'), table_name='admin_actions', schema='core')
    op.drop_index(op.f('ix_core_admin_actions_admin_id'), table_name='admin_actions', schema='core')
    op.drop_table('admin_actions', schema='core')
    op.drop_index(op.f('ix_nearby_places_search_longitude'), table_name='nearby_places')
    op.drop_index(op.f('ix_nearby_places_search_latitude'), table_name='nearby_places')
    op.drop_index(op.f('ix_nearby_places_place_type'), table_name='nearby_places')
    op.drop_index(op.f('ix_nearby_places_place_id'), table_name='nearby_places')
    op.drop_index(op.f('ix_nearby_places_is_active'), table_name='nearby_places')
    op.drop_index(op.f('ix_nearby_places_expires_at'), table_name='nearby_places')
    op.drop_index(op.f('ix_nearby_places_distance_meters'), table_name='nearby_places')
    op.drop_table('nearby_places')
    op.drop_index(op.f('ix_geocode_cache_query_type'), table_name='geocode_cache')
    op.drop_index(op.f('ix_geocode_cache_query_hash'), table_name='geocode_cache')
    op.drop_index(op.f('ix_geocode_cache_is_valid'), table_name='geocode_cache')
    op.drop_index(op.f('ix_geocode_cache_expires_at'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    op.drop_table('videos', schema='core')
    op.drop_table('verification_templates', schema='core')
    op.drop_index(op.f('ix_core_users_firebase_uid'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_table('user_agency', schema='core')
    op.drop_index(op.f('ix_core_system_metrics_timestamp'), table_name='system_metrics', schema='core')
    op.drop_index(op.f('ix_core_system_metrics_metric_name'), table_name='system_metrics', schema='core')
    op.drop_table('system_metrics', schema='core')
    op.drop_index(op.f('ix_core_system_health_status'), table_name='system_health', schema='core')
    op.drop_index(op.f('ix_core_system_health_last_check_at'), table_name='system_health', schema='core')
    op.drop_index(op.f('ix_core_system_health_component_name'), table_name='system_health', schema='core')
    op.drop_table('system_health', schema='core')
    op.drop_index(op.f('ix_core_subscription_plans_plan_code'), table_name='subscription_plans', schema='core')
    op.drop_table('subscription_plans', schema='core')
    op.drop_table('reviews', schema='core')
    op.drop_table('plans', schema='core')
    op.drop_index(op.f('ix_core_performance_metrics_period_type'), table_name='performance_metrics', schema='core')
    op.drop_index(op.f('ix_core_performance_metrics_period_start'), table_name='performance_metrics', schema='core')
    op.drop_index(op.f('ix_core_performance_metrics_metric_type'), table_name='performance_metrics', schema='core')
    op.drop_index(op.f('ix_core_performance_metrics_entity_type'), table_name='performance_metrics', schema='core')
    op.drop_index(op.f('ix_core_performance_metrics_entity_id'), table_name='performance_metrics', schema='core')
    op.drop_table('performance_metrics', schema='core')
    op.drop_index(op.f('ix_core_notification_templates_template_key'), table_name='notification_templates', schema='core')
    op.drop_table('notification_templates', schema='core')
    op.drop_table('leads', schema='core')
    op.drop_table('lead_notes', schema='core')
    op.drop_table('images', schema='core')
    op.drop_index('idx_favorites_user_listing', table_name='favorites', schema='core')
    op.drop_table('favorites', schema='core')
    op.drop_table('agencies', schema='core')
    # ### end Alembic commands ###
